### PR TITLE
Develop Mods checking

### PR DESCRIPTION
**Pull request by KnifMelti**
Starting developing...

### CODE REVIEW

**Comment by KnifMelti** [comment]
This PR has one **breaking change** from the way `AppID-install.ps1` was used earlier (just like https://github.com/Romanitho/Winget-Install/commit/a9da3dd407552646590ae4f77bfa11f057112d6a for **uninstall/uninstalled**).
Now:
- `AppID-install.ps1` : runs during install (before install check)
- `AppID-installed.ps1` : runs after install has been confirmed

Already existing `AppID-install.ps1`/`AppID-uninstall.ps1` must be tested if the work (they earlier executed after install/uninstall had been confirmed)!

**Comment by KnifMelti** [comment]
One final thing...

**Comment by KnifMelti** [comment]
Mods now fully developed 🤯

**Comment by KnifMelti** [comment]
Done 😉

**Comment by Romanitho** [comment]
thanks for that really good feature 👍

**Pull request merged**
