### PR TITLE
Avoiding winget current bug

### PR DESCRIPTION
**Pull request by KnifMelti**
For the moment `winget export -o` has a bug (https://github.com/microsoft/winget-pkgs/issues/152059#issuecomment-2093417362 / https://github.com/microsoft/winget-cli/issues/4440) if the client has certain applications installed.

Testing if a single `Id` is installed via `winget list` is also much faster (<2 sec.)!

### CODE REVIEW

**Comment by Romanitho** [comment]
we used to have that in the past, but for long name that are truncated it was a problem. With the json it was perfect... We are all waiting for a basic json.
But, i'm ok to go back to this solution... waiting for proper job that could use json as output for all commands 😅😅

**Comment by Romanitho** [comment]
moreover you suppose that no other text will appear after the list, which is not 100% sure from our winget dev friends :)

**Comment by Romanitho** [comment]
https://github.com/Romanitho/Winget-Install/commit/77297dc973f49e2675d0b02662446771ae2e7143

**Comment by KnifMelti** [comment]
> [77297dc](https://github.com/Romanitho/Winget-Install/commit/77297dc973f49e2675d0b02662446771ae2e7143)

Ah, forgot about that...
...well, list has its flaws, but I now have to check it this way..  ..too many installed applications that have the bug applying to them in our environment. 
But, you're right about the essentials!

**Comment by KnifMelti** [comment]
Old is more secure in the long run...

**Pull request closed without merging**
