### PR TITLE
Minor changes on Mod functions

### PR DESCRIPTION
**Pull request by Romanitho**
@KnifMelti I made few changes. Do you approve ?

### CODE REVIEW

**Comment by KnifMelti** [comment]
Of course!
Its your code ;)
I was thinking one could call the script with a parameter "-Mods" to trigger the check so it doesn't have to do the filecheck everytime...

**Comment by Romanitho** [comment]
And we could even imagine a `-premod` and a `-postmod` parameters in case you want to run scripts before and/or after winget install.

**Comment by KnifMelti** [comment]
I didn't get it working until I used "$Script:ModsInstall...", but I guess you will...

**Comment by Romanitho** [comment]
Right, i'll fix it now

**Comment by Romanitho** [comment]
should be fixed now :)

**Comment by KnifMelti** [comment]
Ah, so that's the way ;)

**Comment by Romanitho** [comment]
If you confirm that it works, I merge :)

**Comment by KnifMelti** [comment]
Moment, please!

**Comment by KnifMelti** [comment]
As intended when the dialog appeared and until I closed it by uninstalling. Also when I didn't ok the installation.
So, its alright :)

18:16:39 - ###   2022-04-09 - NEW UNINSTALL REQUEST   ###
18:16:39 - Using following Winget Cmd: C:\Users\knifm\AppData\Local\Microsoft\WindowsApps\winget.exe
18:16:40 - TimKosse.FileZilla.Client exists on Winget Repository.
18:16:42 - Uninstalling TimKosse.FileZilla.Client...
18:16:43 - Modifications for TimKosse.FileZilla.Client during uninstall are being applied...
18:16:49 - TimKosse.FileZilla.Client successfully uninstalled.
18:16:52 - ###   END REQUEST   ###

**Pull request merged**
