### PR TITLE
Modifications working...

### PR DESCRIPTION
**Pull request by KnifMelti**
...and FileZilla as an example.

### CODE REVIEW

**Comment by Romanitho** [comment]
Hi, 
thanks for your contributions :)
In my point of view, you can put your mod directly inside the script if you want to use it with SCCM or Intune, as your might package one script per app.
Except if you want to use it for bulk, with mod for several apps at once ?

**Comment by KnifMelti** [comment]
Yes, I could, but I won't :)
Because; were using this as a **Framework** for winget installations in SCCM (as Available applications under Software Center for the user to Install/Uninstall on their own).
Directory structure for the source:
_Winget
 App
  mods
   GetKing.cmd (powershell.exe -Windowstyle hidden -ExecutionPolicy bypass -File "%~dp0winget-install.ps1" %*)
   winget-install.ps1

In this way we only have to create an application in SCCM (for every application we've tested and approved, because there's so many flaws with the winget repo applications which often leads to the users getting a chance to do things in the context of the running process as System) and as Installation/Uninstallation use:
* Installation program: GetKing.cmd -AppIDs TimKosse.FileZilla.Client -WAUWhiteList
* Uninstall program: GetKing.cmd -AppIDs TimKosse.FileZilla.Client -WAUWhiteList -Uninstall

In this way, we can just code a snippet, place it under "mods" and it automatically executes via your installation/uninstallation in **winget-install.ps1**.
Furthermore, **if and when** you implement the Modification structure in **WAU** we can then implement a filecopy/-delete of the mods from the SCCM cache to/from the "mods" directory under "C:\ProgramData\Winget-AutoUpdate"

So, in my mind, this is the ultimate way :)

**Comment by KnifMelti** [comment]
...and never touch the **winget-install.ps1** again (error safe) ;)

**Comment by Romanitho** [comment]
ok, got it. It might be useful indeed.
Regarding several installs at once, I'm thinking about removing this option, because we need to implement the feature to parse the winget native arguments, and in my mind I wanted to keep this install script as simple as possible :)

**Pull request merged**
