### PR TITLE
WAU improvements implementation

### PR DESCRIPTION
**Pull request by Romanitho**
- Review install script to bring new WAU implementations back

### CODE REVIEW

**Comment by KnifMelti** [comment]
Running as system, not detecting UWP Desxktop all the time...
image

**Comment by KnifMelti** [comment]
This is installed:
image

**Comment by KnifMelti** [comment]
System via **NirSoft AdvancedRun** on the left, admin on the rigtht (am I missing something?)...
image

**Comment by Romanitho** [comment]
Thank you, `-AllUsers` missing...

**Comment by Romanitho** [comment]
#93

**Comment by KnifMelti** [comment]
Should we do this in WAU Winget-AutoUpdate-Install.ps1 also?
Can't reproduce it when installing WAU...

**Comment by Romanitho** [comment]
Strange. Should behave the same no?

**Comment by KnifMelti** [comment]
In `winget-install.ps1` you do the test for `Microsoft.VCLibs.140.00.UWPDesktop` every time in the `function Install-Prerequisites`
In `Winget-AutoUpdate-Install.ps1` the test is done once under `function Install-WinGet` therefore we don't notice it...
...I'll add the `-AllUsers` in **WAU** too

**Pull request merged**
